### ISSUE TITLE
"Invalid param" for project_id

### ISSUE THREAD

**Issue by t3db0t** [MCBrandenburg/jiraToClubhouseCLI#1]
I'm doing `go run *.go import --in SearchRequest.xml --projectID 10205 --token dslkfjsldfkjdskflj` and getting `response Body: {"message":"Invalid param: project_id=|10205|"}` for every entry in the file.  I can't dig into the code right at the moment, but I'm not sure what to do.

**Comment by MCBrandenburg** [comment]
@t3db0t 

My apologies for the late response, I have looked into this issue and determined that the projectID you specified is not valid.

I used a valid one which was successful and then made it invalid and received the same error you are seeing.

**Comment by t3db0t** [comment]
That's what I assumed, but the XML clearly has `project_id` fields that read `"10205"` so I'm not sure what the issue is.  Do the pipes in the error response mean anything?

**Comment by MCBrandenburg** [comment]
Okay, I understand now. That is for the Project ID in clubhouse. The CLI doesn't create the project. So you have to do that manually in clubhouse.

**Comment by t3db0t** [comment]
Oh—sigh. If only I had read the readme more carefully.  Thank you!

**Comment by MCBrandenburg** [comment]
@t3db0t It wasn't you, I added that to the readme after I realized there was confusion. Thanks for bringing it to my attention!

**Comment by t3db0t** [comment]
Oh! Haha—the system works ^_^
